
services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    env_file:
      - .env
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - /home/rpodack/data/wordpress:/var/www/html
    networks:
      inception:

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    env_file:
      - .env
    secrets:
      - wp_user_password
      - wp_user
      - wp_admin_user
      - wp_admin_password
    restart: on-failure
    volumes:
      - /home/rpodack/data/wordpress:/var/www/html
    networks:
      inception:

  maraidb:
    build: requirements/mariadb/.
    container_name: mariadb
    env_file:
      - .env
    secrets:
      - db_user
      - db_password
    restart: on-failure
    volumes:
    - /home/rpodack/data/mariadb:/var/lib/mysql
    networks:
      inception:
      
secrets:
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_user:
    file: ../secrets/wp_user.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  db_user:
    file: ../secrets/db_user.txt
  db_password:
    file: ../secrets/db_password.txt
      
networks:
  inception:
